/* Write api/_decks.js from the decks in src/app.html.

   The counter has to know which topic ids are real, or a stray one could fill the database
   with junk fields. That list used to be typed out by hand next to the counter, and when
   two decks were added in September nobody thought to widen it, so every First Date and
   Không Lối Thoát card counted toward the total and then had its topic thrown away. This
   runs from build.sh, so the list cannot fall behind the app again. */
import fs from "node:fs";

const page = fs.readFileSync(new URL("../src/app.html", import.meta.url), "utf8");

function idsIn(name) {
  const at = page.indexOf(`const ${name} = [`);
  if (at < 0) throw new Error(`${name} not found in src/app.html`);
  let i = page.indexOf("[", at), depth = 0, quote = null;
  for (; i < page.length; i++) {
    const c = page[i];
    if (quote) { if (c === "\\") i++; else if (c === quote) quote = null; continue; }
    if (c === '"' || c === "'" || c === "`") { quote = c; continue; }
    if (c === "[") depth++;
    else if (c === "]" && !--depth) break;
  }
  const body = page.slice(at, i);
  return [...body.matchAll(/\{\s*id:\s*"([a-z0-9-]+)"/g)].map(m => m[1]);
}

const ids = [...idsIn("TOPICS"), ...idsIn("TOD")];
const seen = new Set();
for (const id of ids) {
  if (seen.has(id)) throw new Error(`two decks share the id "${id}"`);
  seen.add(id);
}

const out = `/* Generated by tools/decks.mjs from src/app.html. Do not edit: run ./build.sh.
   Every deck the counter will accept a flip for. */
export const DECKS = ${JSON.stringify(ids)};
`;
const path = new URL("../api/_decks.js", import.meta.url);
const before = fs.existsSync(path) ? fs.readFileSync(path, "utf8") : "";
fs.writeFileSync(path, out);
console.log(`decks: ${ids.length}${before === out ? "" : "  (changed)"}`);
