#!/usr/bin/env node
/* Split the card bank in two, after build.sh has assembled index.html.

   src/app.html stays the single source of truth with every card in it. This takes the
   built page and leaves only the free cards in it, moving the rest to api/_bank.js where
   only an entitled request can reach them. A paywall that leaves the cards in the page
   source is decoration, so this step is the whole paywall.

   Every deck costs 5.000đ for 24 hours. Four decks show a few cards first as a trial;
   the rest are dark until paid for. Which cards a trial shows is just authoring order, so
   put the strongest cards at the top of each deck in src/app.html.

   node tools/split.mjs            split index.html in place, write api/_bank.js
   node tools/split.mjs --check    verify no paid card survived in index.html
*/
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const PAGE = path.join(ROOT, "index.html");
const BANK = path.join(ROOT, "api/_bank.js");

/* The trial decks, and how many cards each shows for free. Chosen from real play counts:
   Tình Yêu, Chuyện Ấy, Deep Talk and Chuyện Thiên Hạ are where people already land.
   Every deck not listed here is fully locked. */
const TRIAL = { yeu: 5, ay: 5, triet: 5, doi: 5 };

/* Pull one `const NAME = [ ... ];` array out of the page and read it. Counts brackets rather
   than looking for a marker, so it reads both the hand-written source and its own one-line
   output, which is what makes this script safe to run twice. */
function readArray(src, name) {
  const head = `const ${name} = [`;
  const start = src.indexOf(head);
  if (start === -1) throw new Error(`${name} not found in index.html`);
  const open = start + head.length - 1;
  let depth = 0, quote = "";
  for (let i = open; i < src.length; i++) {
    const c = src[i];
    if (quote) {
      if (c === "\\") i++;
      else if (c === quote) quote = "";
    } else if (c === '"' || c === "'" || c === "`") quote = c;
    else if (c === "[") depth++;
    else if (c === "]" && --depth === 0) {
      return { start, open, end: i + 1, value: eval("(" + src.slice(open, i + 1) + ")") };
    }
  }
  throw new Error(`end of ${name} not found`);
}

const check = process.argv.includes("--check");
let page = fs.readFileSync(PAGE, "utf8");

const topics = readArray(page, "TOPICS");
const tod = readArray(page, "TOD");

const freeOf = id => TRIAL[id] || 0;

/* the free half stays in the page, carrying the true size so the UI can say "50 câu hỏi" */
const freeTopics = topics.value.map(t => ({ ...t, n: t.cards.length, cards: t.cards.slice(0, freeOf(t.id)) }));
const freeTod = tod.value.map(t => ({
  ...t,
  nt: t.truths.length, nd: t.dares.length,
  truths: t.truths.slice(0, freeOf(t.id)),
  dares: t.dares.slice(0, freeOf(t.id)),
}));

/* the paid half moves out of reach */
const paid = {
  topics: Object.fromEntries(topics.value.map(t => [t.id, t.cards.slice(freeOf(t.id))])),
  tod: Object.fromEntries(tod.value.map(t => [t.id, {
    truths: t.truths.slice(freeOf(t.id)),
    dares: t.dares.slice(freeOf(t.id)),
  }])),
};

if (check) {
  const leaked = [];
  for (const [id, cards] of Object.entries(paid.topics)) for (const c of cards) if (page.includes(c)) leaked.push(`${id}: ${c}`);
  for (const [id, deck] of Object.entries(paid.tod)) for (const c of [...deck.truths, ...deck.dares]) if (page.includes(c)) leaked.push(`${id}: ${c}`);
  if (leaked.length) {
    console.error(`${leaked.length} paid card(s) still in index.html:`);
    for (const l of leaked.slice(0, 5)) console.error("  " + l);
    process.exit(1);
  }
  console.log("check: no paid card in index.html");
  process.exit(0);
}

// rewrite the later array first, so the earlier one's offsets still hold
const [a, b] = topics.start < tod.start ? [tod, topics] : [topics, tod];
const replacement = new Map([[topics, JSON.stringify(freeTopics)], [tod, JSON.stringify(freeTod)]]);
for (const arr of [a, b]) page = page.slice(0, arr.open) + replacement.get(arr) + page.slice(arr.end);

fs.writeFileSync(PAGE, page);
fs.writeFileSync(BANK, `/* Generated by tools/split.mjs. The cards a pass pays for.
   Under /api and prefixed with "_", so Vercel never routes it and nobody can fetch it. */
export const BANK = ${JSON.stringify(paid, null, 1)};
`);

const decks = [...freeTopics.map(t => [t.id, t.cards.length, t.n]),
               ...freeTod.map(t => [t.id, t.truths.length + t.dares.length, t.nt + t.nd])];
for (const [id, free, all] of decks) console.log(`  ${id.padEnd(7)} ${String(free).padStart(2)} free / ${all}`);
console.log(`split: ${decks.reduce((n, d) => n + d[1], 0)} free of ${decks.reduce((n, d) => n + d[2], 0)} cards`);
