/* Generated by tools/decks.mjs from src/app.html. Do not edit: run ./build.sh.
   Every deck the counter will accept a flip for. */
export const DECKS = ["yeu","hen","triet","ay","tien","nha","ban","doi","viec","ket","t-yeu","t-ay"];
